src/Entity/HumidityLimit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Cache(usage="READ_ONLY")
 * @ORM\Entity(repositoryClass="App\Repository\HumidityLimitRepository")
 */
class HumidityLimit extends AbstractSensorLimit
{

	/**
	 * @var integer
	 *
	 * @ORM\Id
	 * @ORM\GeneratedValue
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @var string
	 *
	 * @ORM\Column(type="text")
	 */
	private $name;

	/**
	 * @var float
	 *
	 * @ORM\Column(type="float")
	 */
	private $low_alert_value;

	/**
	 * @var float
	 *
	 * @ORM\Column(type="float")
	 */
	private $high_alert_value;

	/**
	 * @var float
	 *
	 * @ORM\Column(type="float")
	 */
	private $low_warning_value;

	/**
	 * @var float
	 *
	 * @ORM\Column(type="float")
	 */
	private $high_warning_value;


	/**
	 * @var Sensor[]
	 *
	 * @ORM\OneToMany(targetEntity="App\Entity\Sensor", mappedBy="humidity_limit")
	 */
	private $sensors;

	/**
	 * HumidityLimit constructor.
	 * @param string $name
	 * @param float $low_alert_value
	 * @param float $high_alert_value
	 * @param float $low_warning_value
	 * @param float $high_warning_value
	 */
	public function __construct($name, $low_alert_value, $high_alert_value, $low_warning_value, $high_warning_value) {
		$this->name = $name;
		$this->low_alert_value = $low_alert_value;
		$this->high_alert_value = $high_alert_value;
		$this->low_warning_value = $low_warning_value;
		$this->high_warning_value = $high_warning_value;
	}

	/**
	 * @return mixed
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * @param mixed $id
	 * @return HumidityLimit
	 */
	public function setId($id) {
		$this->id = $id;

		return $this;
	}

	/**
	 * @return string
	 */
	public function getName() {
		return $this->name;
	}

	/**
	 * @param string $name
	 * @return HumidityLimit
	 */
	public function setName($name) {
		$this->name = $name;

		return $this;
	}

	/**
	 * @return float
	 */
	public function getLowAlertValue(): float {
		return $this->low_alert_value;
	}

	/**
	 * @param float $low_alert_value
	 * @return HumidityLimit
	 */
	public function setLowAlertValue(float $low_alert_value): HumidityLimit {
		$this->low_alert_value = $low_alert_value;

		return $this;
	}

	/**
	 * @return float
	 */
	public function getHighAlertValue(): float {
		return $this->high_alert_value;
	}

	/**
	 * @param float $high_alert_value
	 * @return HumidityLimit
	 */
	public function setHighAlertValue(float $high_alert_value): HumidityLimit {
		$this->high_alert_value = $high_alert_value;

		return $this;
	}

	/**
	 * @return float
	 */
	public function getLowWarningValue(): float {
		return $this->low_warning_value;
	}

	/**
	 * @param float $low_warning_value
	 * @return HumidityLimit
	 */
	public function setLowWarningValue(float $low_warning_value): HumidityLimit {
		$this->low_warning_value = $low_warning_value;

		return $this;
	}

	/**
	 * @return float
	 */
	public function getHighWarningValue(): float {
		return $this->high_warning_value;
	}

	/**
	 * @param float $high_warning_value
	 * @return HumidityLimit
	 */
	public function setHighWarningValue(float $high_warning_value): HumidityLimit {
		$this->high_warning_value = $high_warning_value;

		return $this;
	}

	/**
	 * @return Sensor[]
	 */
	public function getSensors() {
		return $this->sensors;
	}

	/**
	 * @param Sensor[] $sensors
	 * @return HumidityLimit
	 */
	public function setSensors($sensors) {
		$this->sensors = $sensors;

		return $this;
	}

    public function __toString()
    {
        return $this->getLowAlertValue() . ' < ' . $this->getLowWarningValue() . ' < EXP > ' . $this->getHighWarningValue() . ' > ' . $this->getHighAlertValue();
    }

}

src/Entity/Sensor.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Groups;

/**
 * @ORM\Cache(usage="READ_ONLY")
 * @ORM\Entity(repositoryClass="App\Repository\SensorRepository")
 */
class Sensor
{
    /**
	 * @var integer
	 *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
	 * @Groups({"updateSensorData"})
     */
    private $id;

	/**
	 * @var string
	 *
	 * @ORM\Column(type="text")
	 */
	private $name;

	/**
	 * @var string
	 *
	 * @ORM\Column(type="text")
	 */
	private $type;

	/**
	 * @var integer
	 *
	 * @ORM\Column(type="smallint")
	 */
	private $gpio;

	/**
	 * @var Db
	 *
	 * @ORM\ManyToOne(targetEntity="App\Entity\Db", inversedBy="db")
	 * @ORM\JoinColumn(name="db_id", referencedColumnName="id")
	 */
	private $db;

	/**
	 * @var TemperatureLimit
	 *
	 * @ORM\ManyToOne(targetEntity="App\Entity\TemperatureLimit", inversedBy="sensors")
	 * @ORM\JoinColumn(name="temperature_limit_id", referencedColumnName="id")
	 * @ORM\Cache(usage="READ_ONLY")
	 */
	private $temperature_limit;

	/**
	 * @var HumidityLimit
	 *
	 * @ORM\ManyToOne(targetEntity="App\Entity\HumidityLimit", inversedBy="sensors")
	 * @ORM\JoinColumn(name="humidity_limit_id", referencedColumnName="id")
	 * @ORM\Cache(usage="READ_ONLY")
	 */
	private $humidity_limit;

	/**
	 * @return int
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * @param int $id
	 * @return Sensor
	 */
	public function setId($id) {
		$this->id = $id;

		return $this;
	}

	/**
	 * @return string
	 */
	public function getName() {
		return $this->name;
	}

	/**
	 * @param string $name
	 * @return Sensor
	 */
	public function setName($name) {
		$this->name = $name;
		return $this;
	}

	/**
	 * @return string
	 */
	public function getType() {
		return $this->type;
	}

	/**
	 * @param string $type
	 * @return Sensor
	 */
	public function setType($type) {
		$this->type = $type;

		return $this;
	}

	/**
	 * @return int
	 */
	public function getGpio() {
		return $this->gpio;
	}

	/**
	 * @param int $gpio
	 * @return Sensor
	 */
	public function setGpio($gpio) {
		$this->gpio = $gpio;

		return $this;
	}

	/**
	 * @return TemperatureLimit
	 */
	public function getTemperatureLimit() {
		return $this->temperature_limit;
	}

	/**
	 * @param TemperatureLimit $temperature_limit
	 * @return Sensor
	 */
	public function setTemperatureLimit($temperature_limit) {
		$this->temperature_limit = $temperature_limit;

		return $this;
	}

	/**
	 * @return HumidityLimit
	 */
	public function getHumidityLimit() {
		return $this->humidity_limit;
	}

	/**
	 * @param HumidityLimit $humidity_limit
	 * @return Sensor
	 */
	public function setHumidityLimit($humidity_limit) {
		$this->humidity_limit = $humidity_limit;

		return $this;
	}

	/**
	 * @return Db
	 */
	public function getDb() {
		return $this->db;
	}

	/**
	 * @param Db $db
	 * @return Sensor
	 */
	public function setDb($db) {
		$this->db = $db;

		return $this;
	}

}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>{% block title %}Cellar{% endblock %}</title>

        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        {% block stylesheets %}
            <style>
                .huge {
                    font-size: 40px;
                }
            </style>
        {% endblock %}
    </head>
    <body>
        <div class="container-fluid">
            {% block body %}{% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/fr.js"></script>

        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/cellar.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="row">
        <img src="/cellar.png" />
		<div id="sensor_1" style="position: absolute; top: 400px; left: 750px;"></div>
		<div id="sensor_2" style="position: absolute; top: 670px; left: 750px;"></div>
		<div id="sensor_3" style="position: absolute; top: 280px; left: 780px;"></div>
		<div id="sensor_7" style="position: absolute; top: 630px; left: 130px;"></div>
		<div id="sensor_8" style="position: absolute; top: 60px;  left: 410px;"></div>
		<div id="sensor_9" style="position: absolute; top: 170px; left: 580px;"></div>
	</div>

{% endblock %}

{% block javascripts %}
	<script type="text/javascript">
		var ws;
		(function () {
			'use strict';

			var _receiver = document.getElementById('ws-content-receiver');
			ws = new WebSocket('wss://{{ ws_url }}');

			ws.onopen = function () {
				//_receiver.innerHTML = 'Connected !';
			};

			ws.onmessage = function (event) {
				try {
					var sensor_raw_data = JSON.parse(event.data);
					console.log(sensor_raw_data);

					for(var k in sensor_raw_data.sensor_data) {
						const sensor_data = sensor_raw_data.sensor_data[k];
						const sid = sensor_data.sensor.id;

						const temp = Math.round(sensor_data.temperature * 100) / 100;
						const humi = Math.round(sensor_data.humidity * 10) / 10;
						$('#sensor_' + sid).html(temp + "°C<br />" + humi + "%");
					}
				} catch (error) {
					console.log(error);
				}
			};

			ws.onclose = function () {
			};

			ws.onerror = function () {
			};
		})();
	</script>
{% endblock %}

templates/chromecast.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Cellar</title>
    <style type="text/css">
        html {
            height: 100%;
            padding: 0;
            width: 100%;
        }

        body {
            overflow: hidden;
            height: 100%;
            padding: 0;
            margin: 0;
            background: black url("/logo.png") no-repeat 50% 50%;
        }

        #main {
            height: 100%;
            background: black url("/logo.png") no-repeat 50% 50%;
            opacity: 0;
            transition: opacity 4s ease;
        }

        #main, iframe {
            background: black url("/logo.png") no-repeat 50% 50%;
        }

        #main.show {
            opacity: 1;
        }

        #status {
            transition: opacity 1s;
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            color: #555;
            font-weight: bold;
            height: 1.2em;
            text-align: center;
            padding: 10px;
            background: rgba(32, 27, 37, 0.9);
            z-index: 10;
        }

        #status.empty {
            opacity: 0;
        }

        iframe {
            position: absolute;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            opacity: 0;
            transition: opacity 0;
            width: 100%;
            height: 100%;
            border: 0 transparent;
        }

        iframe.show {
            transition: opacity 1s;
            opacity: 1;
        }

    </style>
</head>
<body id="dcast">

    <cast-media-player id="player"></cast-media-player>

    <div id="main" class="fade">
        <iframe id="if1"></iframe>
    </div>
    <div id="status" class="empty">
    </div>

    <script type="text/javascript" src="//www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js">
    </script>
    <script>
        var reload_time = 0;
        var timer_id = null;

        window.onload = function () {
            var main = document.getElementById('main');
            var status = document.getElementById('status');

            var if1 = document.getElementById('if1');

            main.classList.add('show');

            function setStatus(msg) {
                if (msg) {
                    status.classList.remove('empty');
                }
                else {
                    status.classList.add('empty');
                }
                status.textContent = msg;
            }

            if1.onload = function (e) {
                setStatus('');
            };

            function loadFrame(url) {
                setStatus('Loading: ' + url);
                if1.src = url;
            }

            const context = cast.framework.CastReceiverContext.getInstance();
            const playerManager = context.getPlayerManager();

            playerManager.addEventListener(cast.framework.events.EventType.ALL, function (event) {
                console.log(event.type, event);
            });

            const CUSTOM_CHANNEL = 'urn:x-cast:fr.cellar.arbey.cast';
            context.addCustomMessageListener(CUSTOM_CHANNEL, function (event) {
                url = event.data.url;
                setStatus('Loading: ' + url);
                if1.src = url;
                if1.style.zIndex = 3;
                if1.classList.add('show');
                context.sendCustomMessage(CUSTOM_CHANNEL, event.senderId, event.data);
            });

            context.start({statusText: 'Application is starting'});
        };
    </script>
</body>
</html>

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="row" style="display: flex; width: 100%">
	<div class="col" style="display: flex; margin: 0 auto">
		<div class="container-fluid">
			<h1 style="text-align: center;">Cellar - {{ db.name }}{# - <span id="date">Du <input type="date" id="from" value="{{ from|date('Y-m-d') }}"> Au <input type="date" id="to" value="{{ to|date('Y-m-d') }}"></span>#}</h1>
			<div class="row">
                {% for color, nb in stats_color %}
					<div class="row text-black" style="display: flex; width: 350px">
						<div class="col" style="display: flex; margin: auto">{{ color }} :</div>
						<div class="col" style="display: flex; margin: auto">{{ nb }}</div>
					</div>
                {% endfor %}
			</div>
			<div class="row">
				&nbsp;
			</div>
			<div class="row">
				&nbsp;
			</div>
			<div class="row">
                {% for bottle_name, bottle_data in stats_bottle_size %}
					<div class="row text-black" style="display: flex; width: 350px">
						<div class="col" style="display: flex; margin: auto">{{ bottle_name }} ({{ bottle_data.capacity }}) :</div>
						<div class="col" style="display: flex; margin: auto">{{ bottle_data.nb }}</div>
					</div>
                {% endfor %}
			</div>
			<div class="row">
				&nbsp;
			</div>
			<div class="row">
				&nbsp;
			</div>
			<div class="row">
                {{ pairing|nl2br }}
			</div>
		</div>
	</div>
	<div class="col" style="flex: 0">
		<div class="container border border-dark" style="width: 350px">
			<div class="row text-white bg-dark" style="display: flex; height: 2em">
				<div class="col text-center" style="margin: auto">Actuellement</div>
			</div>
			{% for sensor in db.sensors %}
			<div class="row text-white bg-secondary" style="display: flex; height: 5em">
				<div class="col" style="display: flex; margin: auto">
					{{ sensor.name }} :
				</div>
				<div class="col" style="display: flex; margin: auto" id="sensor_{{ sensor.id }}_temperature_state">
					<div style="margin: auto"><i class="fa fa-thermometer-quarter" id="sensor_{{ sensor.id }}_temperature_icon"></i></div>
					<div id="sensor_{{ sensor.id }}_temperature_value">???</div>
				</div>
				<div class="col" style="display: flex; margin: auto" id="sensor_{{ sensor.id }}_humidity_state">
					<div style="margin: auto"><i class="fa fa-tint" id="sensor_{{ sensor.id }}_humidity_icon"></i></div>
					<div id="sensor_{{ sensor.id }}_humidity_value">???</div>
				</div>
			</div>
			{% endfor %}

		</div>
	</div>
</div>
{% endblock %}

{% block javascripts %}
	<script type="text/javascript">
		(function () {
			'use strict';

			var url = new URL(window.location.href);
			var from = url.searchParams.get('from');
			var to = url.searchParams.get('to');

			$('#from').change(function () {
				var from_timestamp = (new Date($(this).val())).getTime() / 1000;
				window.location = '/{{ db.id }}?from=' + from_timestamp + ((to != null) ? '&to=' + to : '');
			});

			$('#to').change(function () {
				var to_timestamp = ((new Date($(this).val())).getTime() / 1000) + 24*3600 - 1;
				window.location = '/{{ db.id }}?to=' + to_timestamp + ((from != null) ? '&from=' + from : '');
			});

			var sensors_definition = [];
			{% for sensor in db.sensors %}
				sensors_definition[{{ sensor.id }}] = {
					temperature_limit: {
						low_alert_value: {{ sensor.temperatureLimit.lowAlertValue }},
						high_alert_value: {{ sensor.temperatureLimit.highAlertValue }},
						low_warning_value: {{ sensor.temperatureLimit.lowWarningValue }},
						high_warning_value: {{ sensor.temperatureLimit.highWarningValue }}
					},
					humidity_limit: {
						low_alert_value: {{ sensor.humidityLimit.lowAlertValue }},
						high_alert_value: {{ sensor.humidityLimit.highAlertValue }},
						low_warning_value: {{ sensor.humidityLimit.lowWarningValue }},
						high_warning_value: {{ sensor.humidityLimit.highWarningValue }}
					}
				};
			{% endfor %}

			var _receiver = document.getElementById('ws_status');
			var ws = new WebSocket('wss://{{ ws_url }}');

			ws.onmessage = function (event) {
				try {
					var sensor_raw_data = JSON.parse(event.data);
					console.log(sensor_raw_data);

					var header_content = [];
					for(var k in sensor_raw_data.sensor_data) {
						var sensor_data = sensor_raw_data.sensor_data[k];
						var sid = sensor_data.sensor.id;

						if (sensors_definition[sid]) {
                            $('#sensor_' + sid + '_temperature_value').html(sensor_data.temperature + '°C');
                            var state_sel = $('#sensor_' + sid + '_temperature_state');
                            //state_sel.removeClass().addClass('row text-white');
                            var limit = sensors_definition[sid].temperature_limit;
                            if ((sensor_data.temperature < limit.low_alert_value) || (sensor_data.temperature > limit.high_alert_value)) {
                                state_sel.addClass('bg-danger');
                            } else if ((sensor_data.temperature < limit.low_warning_value) || (sensor_data.temperature > limit.high_warning_value)) {
                                state_sel.addClass('bg-warning');
                            } else {
                                state_sel.addClass('bg-success');
                            }

                            $('#sensor_' + sid + '_humidity_value').html(sensor_data.humidity + '%');
                            var state_sel = $('#sensor_' + sid + '_humidity_state');
                            //state_sel.removeClass().addClass('row text-white');
                            limit = sensors_definition[sid].humidity_limit;
                            if ((sensor_data.humidity < limit.low_alert_value) || (sensor_data.humidity > limit.high_alert_value)) {
                                state_sel.addClass('bg-danger');
                            } else if ((sensor_data.humidity < limit.low_warning_value) || (sensor_data.humidity > limit.high_warning_value)) {
                                state_sel.addClass('bg-warning');
                            } else {
                                state_sel.addClass('bg-success');
                            }
                        }
					}
				} catch (error) {
					console.log(error);
				}
			};

			ws.onclose = function () {
			};

			ws.onerror = function () {
			};
		})();
	</script>
{% endblock %}

templates/import.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h1>Cellar - Test</h1>
{% endblock %}

{% block javascripts %}
{% endblock %}

templates/pairing.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h1>Cellar - {{ db.name }}</h1>

	<div class="row">
        <pre>
            {{ pairing }}
        </pre>
	</div>
{% endblock %}

templates/temperature.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h1>Cellar - {{ db.name }} - <span id="date">Du <input type="date" id="from" value="{{ from|date('Y-m-d') }}"> Au <input type="date" id="to" value="{{ to|date('Y-m-d') }}"></span></h1>
	<div id="ws-content-receiver">
		Connecting...
	</div>

	<div class="row">
        {% for sensor in db.sensors %}
			<div class="col">
				<div class="card text-white bg-success" id="sensor_{{ sensor.id }}_temperature_state">
					<div class="card-header">
						<div class="card-body">
							<div class="row">
								<div class="col">
									<i class="fa fa-thermometer-quarter fa-5x" id="sensor_{{ sensor.id }}_temperature_icon"></i>
								</div>
								<div class="col text-right">
									<div class="huge" id="sensor_{{ sensor.id }}_temperature_value">???</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        {% endfor %}
	</div>
	<div class="row">
        {% for sensor in db.sensors %}
			<div class="col">
				<div class="card text-white bg-success" id="sensor_{{ sensor.id }}_humidity_state">
					<div class="card-header">
						<div class="card-body">
							<div class="row">
								<div class="col">
									<i class="fa fa-tint fa-5x" id="sensor_{{ sensor.id }}_humidity_icon"></i>
								</div>
								<div class="col text-right">
									<div class="huge" id="sensor_{{ sensor.id }}_humidity_value">???</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        {% endfor %}
	</div>

    {% for sensor in db.sensors %}
		<div class="row">
			<div class="col"><img src="/api/{{ db.id }}/sensors/{{ sensor.id }}/graph/temperature?from={{ from|date('U') }}&to={{ to|date('U') }}" id="sensor_{{ sensor.id }}_temperature_graph" /></div>
			<div class="col"><img src="/api/{{ db.id }}/sensors/{{ sensor.id }}/graph/humidity?from={{ from|date('U') }}&to={{ to|date('U') }}" id="sensor_{{ sensor.id }}_humidity_graph" /></div>
		</div>
    {% endfor %}
{% endblock %}

{% block javascripts %}
	<script type="text/javascript">
        var ws;
        (function () {
            'use strict';

            var url = new URL(window.location.href);
            var from = url.searchParams.get('from');
            var to = url.searchParams.get('to');

            $('#from').change(function () {
                var from_timestamp = (new Date($(this).val())).getTime() / 1000;
                window.location = '/{{ db.id }}/temperature?from=' + from_timestamp + ((to != null) ? '&to=' + to : '');
            });

            $('#to').change(function () {
                var to_timestamp = ((new Date($(this).val())).getTime() / 1000) + 24*3600 - 1;
                window.location = '/{{ db.id }}/temperature?to=' + to_timestamp + ((from != null) ? '&from=' + from : '');
            });

            var sensors_definition = [];
            {% for sensor in db.sensors %}
            sensors_definition[{{ sensor.id }}] = {
                temperature_limit: {
                    low_alert_value: {{ sensor.temperatureLimit.lowAlertValue }},
                    high_alert_value: {{ sensor.temperatureLimit.highAlertValue }},
                    low_warning_value: {{ sensor.temperatureLimit.lowWarningValue }},
                    high_warning_value: {{ sensor.temperatureLimit.highWarningValue }}
                },
                humidity_limit: {
                    low_alert_value: {{ sensor.humidityLimit.lowAlertValue }},
                    high_alert_value: {{ sensor.humidityLimit.highAlertValue }},
                    low_warning_value: {{ sensor.humidityLimit.lowWarningValue }},
                    high_warning_value: {{ sensor.humidityLimit.highWarningValue }}
                }
            };
            {% endfor %}

            var _receiver = document.getElementById('ws-content-receiver');
            ws = new WebSocket('wss://{{ ws_url }}');

            ws.onopen = function () {
                _receiver.innerHTML = 'Connected !';
            };

            ws.onmessage = function (event) {
                try {
                    var sensor_raw_data = JSON.parse(event.data);
                    console.log(sensor_raw_data);

                    _receiver.innerHTML = 'Connected (@' + sensor_raw_data.date + ')';

                    var header_content = [];
                    for(var k in sensor_raw_data.sensor_data) {
                        var sensor_data = sensor_raw_data.sensor_data[k];
                        var sid = sensor_data.sensor.id;

                        if (sensors_definition[sid] == null) continue;

                        const temp = Math.round(sensor_data.temperature * 100) / 100;
                        const humi = Math.round(sensor_data.humidity * 10) / 10;

                        $('#sensor_' + sid + '_temperature_value').html(temp + '°C');
                        var state_sel = $('#sensor_' + sid + '_temperature_state');
                        state_sel.removeClass().addClass('card text-white');
                        var limit = sensors_definition[sid].temperature_limit;
                        if ((sensor_data.temperature < limit.low_alert_value) || (sensor_data.temperature > limit.high_alert_value)) {
                            state_sel.addClass('bg-danger');
                        } else if ((sensor_data.temperature < limit.low_warning_value) || (sensor_data.temperature > limit.high_warning_value)) {
                            state_sel.addClass('bg-warning');
                        } else {
                            state_sel.addClass('bg-success');
                        }

                        $('#sensor_' + sid + '_humidity_value').html(humi + '%');
                        var state_sel = $('#sensor_' + sid + '_humidity_state');
                        state_sel.removeClass().addClass('card text-white');
                        limit = sensors_definition[sid].humidity_limit;
                        if ((sensor_data.humidity < limit.low_alert_value) || (sensor_data.humidity > limit.high_alert_value)) {
                            state_sel.addClass('bg-danger');
                        } else if ((sensor_data.humidity < limit.low_warning_value) || (sensor_data.humidity > limit.high_warning_value)) {
                            state_sel.addClass('bg-warning');
                        } else {
                            state_sel.addClass('bg-success');
                        }
                    }
                } catch (error) {
                    console.log(error);
                }
            };

            ws.onclose = function () {
            };

            ws.onerror = function () {
            };

            setInterval(refreshGraphs, 300000);
        })();

        function refreshGraphs() {
            var to = new Date(Date.now());
            var from = new Date(Date.now() - 86400000);
            console.log("Refresh @" + to.getTime());
            {% for sensor in db.sensors %}
            $('#sensor_{{ sensor.id }}_temperature_graph').attr("src", "/api/{{ db.id }}/sensors/{{ sensor.id }}/graph/temperature?from=" + (from.getTime() / 1000) + "&to=" + (to.getTime() / 1000));
            $('#sensor_{{ sensor.id }}_humidity_graph').attr("src", "/api/{{ db.id }}/sensors/{{ sensor.id }}/graph/humidity?from=" + (from.getTime() / 1000) + "&to=" + (to.getTime() / 1000));
            {% endfor %}
        }
	</script>
{% endblock %}

templates/test.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h1>Cellar - Test</h1>
{% endblock %}

{% block javascripts %}
{% endblock %}